Maybe works with TooN2?
Fixed up new serialization.

Removed parts of GVars2 compatibility which are incompatible with TooN2.

Vector<-1> will fail nastily.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3486,6 +3486,54 @@ _ACEOF
 		{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 	fi
+
+	{ echo "$as_me:$LINENO: checking for TooN-2" >&5
+echo $ECHO_N "checking for TooN-2... $ECHO_C" >&6; }
+
+	a=
+	cat >conftest.$ac_ext <<_ACEOF
+#include <TooN/TooN.h>
+int main(){TooN::Vector<2, float> v;return 0;}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  a=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+	if test x$a = x1
+	then
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+		cat >>confdefs.h <<\_ACEOF
+#define GVARS3_HAVE_TOON2 1
+_ACEOF
+
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+	fi
 fi
 
 
